# version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: /api
        VITE_EMAILJS_SERVICE_ID: ${VITE_EMAILJS_SERVICE_ID}
        VITE_EMAILJS_TEMPLATE_ID: ${VITE_EMAILJS_TEMPLATE_ID}
        VITE_EMAILJS_PUBLIC_KEY: ${VITE_EMAILJS_PUBLIC_KEY}
        VITE_DIGIKEY_CLIENT_ID: ${VITE_DIGIKEY_CLIENT_ID}
        VITE_DIGIKEY_CLIENT_SECRET: ${VITE_DIGIKEY_CLIENT_SECRET}
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    env_file:
      - ./.env
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - TZ=Asia/Ho_Chi_Minh
    env_file:
      - ./.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - app-network
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared_tunnel
    restart: always
    command: tunnel run
    volumes:
      - ./cloudflared:/etc/cloudflared
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge