tunnel: efdcf16b-d285-47ff-8c3b-8241c386198f
credentials-file: /etc/cloudflared/efdcf16b-d285-47ff-8c3b-8241c386198f.json

ingress:
  # uploads
  - hostname: erpst.io.vn
    path: "^/uploads/.*"
    service: http://backend:3000

  # api
  - hostname: erpst.io.vn
    path: "^/api/.*"
    service: http://backend:3000

  # frontend
  - hostname: erpst.io.vn
    service: http://frontend:80

  # ai
  - hostname: ai.erpst.io.vn
    service: http://ollama:11434

  - service: http_status:404
