/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    ButtonAdd: typeof import('./src/components/Button-Add.vue')['default']
    ButtonAgree: typeof import('./src/components/Button-Agree.vue')['default']
    ButtonBack: typeof import('./src/components/Button-Back.vue')['default']
    ButtonCancel: typeof import('./src/components/Button-Cancel.vue')['default']
    ButtonDelete: typeof import('./src/components/Button-Delete.vue')['default']
    ButtonDownload: typeof import('./src/components/Button-Download.vue')['default']
    ButtonDownloadIcon: typeof import('./src/components/Button-Download-Icon.vue')['default']
    ButtonEdit: typeof import('./src/components/Button-Edit.vue')['default']
    ButtonEye: typeof import('./src/components/Button-Eye.vue')['default']
    ButtonHistoryExport: typeof import('./src/components/Button-History-Export.vue')['default']
    ButtonImportFile: typeof import('./src/components/Button-ImportFile.vue')['default']
    ButtonNextManufacture: typeof import('./src/components/Button-Next-Manufacture.vue')['default']
    ButtonRemove: typeof import('./src/components/Button-Remove.vue')['default']
    ButtonSave: typeof import('./src/components/Button-Save.vue')['default']
    ButtonSearch: typeof import('./src/components/Button-Search.vue')['default']
    InputDate: typeof import('./src/components/Input-Date.vue')['default']
    InputField: typeof import('./src/components/Input-Field.vue')['default']
    InputFiles: typeof import('./src/components/Input-Files.vue')['default']
    InputSearch: typeof import('./src/components/Input-Search.vue')['default']
    InputSelect: typeof import('./src/components/Input-Select.vue')['default']
    InputTextarea: typeof import('./src/components/Input-Textarea.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SnackbarCaution: typeof import('./src/components/Snackbar-Caution.vue')['default']
    SnackbarFailed: typeof import('./src/components/Snackbar-Failed.vue')['default']
    SnackbarSuccess: typeof import('./src/components/Snackbar-Success.vue')['default']
    Toolbar: typeof import('./src/components/Toolbar.vue')['default']
  }
}
