/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/Page-Dashboard/Page-Dashboard': RouteRecordInfo<'/Page-Dashboard/Page-Dashboard', '/Page-Dashboard/Page-Dashboard', Record<never, never>, Record<never, never>>,
    '/Page-Project/Page-Project': RouteRecordInfo<'/Page-Project/Page-Project', '/Page-Project/Page-Project', Record<never, never>, Record<never, never>>,
    '/Page-Setting/Page-Login': RouteRecordInfo<'/Page-Setting/Page-Login', '/Page-Setting/Page-Login', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/Page-Dashboard/Page-Dashboard.vue': {
      routes: '/Page-Dashboard/Page-Dashboard'
      views: never
    }
    'src/pages/Page-Project/Page-Project.vue': {
      routes: '/Page-Project/Page-Project'
      views: never
    }
    'src/pages/Page-Setting/Page-Login.vue': {
      routes: '/Page-Setting/Page-Login'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
